import java.io.*;
import java.sql.*;
import java.io.IOException;
import java.util.*;

/**
 ProductRecommenderUtility class consists of utility functions required for recommendation feature.
*/
public class ProductRecommenderUtility{
	
	static Connection conn = null;
    static String message;
	
	public static String getConnection()
	{

		try
		{
			Class.forName("com.mysql.jdbc.Driver").newInstance();
			conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/digicart","root","root");							
			message="Successfull";
			return message;
		}
		catch(SQLException e)
		{
			 message="unsuccessful";
		     return message;
		}
		catch(Exception e)
		{
			 message="unsuccessful";
		     return message;
		}
	}

	/**
		The recommendations generated by the SVD algo i.e. output.csv is read and details are stored in hashMap.
	*/
	public HashMap<String,String> readOutputFile(){

		String TOMCAT_HOME = System.getProperty("catalina.home");
        BufferedReader br = null;
        String line = "";
        String cvsSplitBy = ",";
		HashMap<String,String> prodRecmMap = new HashMap<String,String>();
		try {

            br = new BufferedReader(new FileReader(new File(TOMCAT_HOME+"\\webapps\\DigiCart\\output.csv")));
            while ((line = br.readLine()) != null) {

                // use comma as separator
                String[] prod_recm = line.split(cvsSplitBy,2);
				prodRecmMap.put(prod_recm[0],prod_recm[1]);
            }
			
		} catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            if (br != null) {
                try {
                    br.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
		}
		
		return prodRecmMap;
	}
	
	/**
		Product data is fetched from database using ProductId.
		@param productId identifier for the product
	*/
	public static Product getProduct(String productId){
		Product prodObj = new Product();
		try 
		{
			String msg = getConnection();
			String selectProd="select * from  Products where Id=?";
			PreparedStatement pst = conn.prepareStatement(selectProd);
			pst.setString(1,productId);
			ResultSet rs = pst.executeQuery();
		
			while(rs.next())
			{	
				prodObj = new Product(
				rs.getString("id"),
				rs.getString("asin"),
				rs.getString("brand"),
				rs.getString("categories"),
				rs.getString("colors"),
				rs.getString("dateAdded"),
				rs.getString("dateUpdated"), 
				rs.getString("dimensions"),
				rs.getString("ean"), 
				rs.getString("imageURLs"),
				rs.getString("manufacturer"),
				rs.getString("manufacturerNumber"),
				rs.getString("productName"),
				rs.getString("primaryCategories"),
				rs.getString("weight"));
			}
			rs.close();
			pst.close();
			conn.close();
		}
		catch(Exception e)
		{
		}
		return prodObj;	
	}
}